USE KA_FASHION_BD;
GO

IF OBJECT_ID('dbo.FIDE_ESTADOS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_ESTADOS_TB (
    ID_ESTADO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_ESTADO NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_FIDE_ESTADOS_TB PRIMARY KEY (ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_CATEGORIAS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_CATEGORIAS_TB (
    ID_CATEGORIA INT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_CATEGORIAS_TB PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT FK_CATEGORIAS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_SUCURSALES_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_SUCURSALES_TB (
    ID_SUCURSAL INT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    DIRECCION NVARCHAR(255) NULL,
    TELEFONO NVARCHAR(20) NULL,
    HORARIO NVARCHAR(100) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_SUCURSALES_TB PRIMARY KEY (ID_SUCURSAL),
    CONSTRAINT FK_SUCURSALES_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_PRODUCTOS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_PRODUCTOS_TB (
    ID_PRODUCTO INT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(150) NOT NULL,
    DESCRIPCION NVARCHAR(500) NULL,
    PRECIO DECIMAL(18,2) NOT NULL,
    IMAGEN NVARCHAR(255) NULL,
    TALLA NVARCHAR(20) NULL,
    COLOR NVARCHAR(50) NULL,
    DESTACADO BIT NOT NULL DEFAULT (0),
    NOVEDAD BIT NOT NULL DEFAULT (0),
    ID_CATEGORIA INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_PRODUCTOS_TB PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES dbo.FIDE_CATEGORIAS_TB(ID_CATEGORIA),
    CONSTRAINT FK_PRODUCTOS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_INVENTARIO_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_INVENTARIO_TB (
    ID_INVENTARIO INT IDENTITY(1,1) NOT NULL,
    TALLA NVARCHAR(20) NULL,
    COLOR NVARCHAR(50) NULL,
    EXISTENCIAS INT NOT NULL DEFAULT (0),
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT (GETDATE()),
    ID_PRODUCTO INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_INVENTARIO_TB PRIMARY KEY (ID_INVENTARIO),
    CONSTRAINT FK_INVENTARIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES dbo.FIDE_PRODUCTOS_TB(ID_PRODUCTO),
    CONSTRAINT FK_INVENTARIO_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES dbo.FIDE_SUCURSALES_TB(ID_SUCURSAL),
    CONSTRAINT FK_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_CARRITOS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_CARRITOS_TB (
    ID_CARRITO INT IDENTITY(1,1) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT (GETDATE()),
    ID_USUARIO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_CARRITOS_TB PRIMARY KEY (ID_CARRITO),
    CONSTRAINT FK_CARRITOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.tbUsuario(Consecutivo),
    CONSTRAINT FK_CARRITOS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_CARRITO_DETALLES_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_CARRITO_DETALLES_TB (
    ID_DETALLE_CARRITO INT IDENTITY(1,1) NOT NULL,
    CANTIDAD INT NOT NULL,
    TALLA NVARCHAR(20) NULL,
    COLOR NVARCHAR(50) NULL,
    ID_CARRITO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT PK_FIDE_CARRITO_DETALLES_TB PRIMARY KEY (ID_DETALLE_CARRITO),
    CONSTRAINT FK_CARRITODET_CARRITO FOREIGN KEY (ID_CARRITO) REFERENCES dbo.FIDE_CARRITOS_TB(ID_CARRITO),
    CONSTRAINT FK_CARRITODET_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES dbo.FIDE_PRODUCTOS_TB(ID_PRODUCTO)
);
GO

IF OBJECT_ID('dbo.FIDE_PEDIDOS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_PEDIDOS_TB (
    ID_PEDIDO INT IDENTITY(1,1) NOT NULL,
    METODO_ENTREGA NVARCHAR(50) NULL,
    OBSERVACIONES NVARCHAR(255) NULL,
    TOTAL DECIMAL(18,2) NOT NULL,
    FECHA_PEDIDO DATETIME NOT NULL DEFAULT (GETDATE()),
    ID_USUARIO INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_PEDIDOS_TB PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.tbUsuario(Consecutivo),
    CONSTRAINT FK_PEDIDOS_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES dbo.FIDE_SUCURSALES_TB(ID_SUCURSAL),
    CONSTRAINT FK_PEDIDOS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_PEDIDOS_DETALLE_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_PEDIDOS_DETALLE_TB (
    ID_DETALLE INT IDENTITY(1,1) NOT NULL,
    CANTIDAD INT NOT NULL,
    TALLA NVARCHAR(20) NULL,
    COLOR NVARCHAR(50) NULL,
    PRECIO_UNITARIO DECIMAL(18,2) NOT NULL,
    SUBTOTAL DECIMAL(18,2) NOT NULL,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT PK_FIDE_PEDIDOS_DETALLE_TB PRIMARY KEY (ID_DETALLE),
    CONSTRAINT FK_PEDIDOSDET_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES dbo.FIDE_PEDIDOS_TB(ID_PEDIDO),
    CONSTRAINT FK_PEDIDOSDET_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES dbo.FIDE_PRODUCTOS_TB(ID_PRODUCTO)
);
GO

IF OBJECT_ID('dbo.FIDE_PROMOCIONES_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_PROMOCIONES_TB (
    ID_PROMOCION INT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(255) NULL,
    DESCUENTO DECIMAL(18,2) NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_PROMOCIONES_TB PRIMARY KEY (ID_PROMOCION),
    CONSTRAINT FK_PROMOCIONES_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_PROMO_PRODUCTOS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_PROMO_PRODUCTOS_TB (
    ID_PRODUCTO INT NOT NULL,
    ID_PROMOCION INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_PROMO_PRODUCTOS_TB PRIMARY KEY (ID_PRODUCTO, ID_PROMOCION),
    CONSTRAINT FK_PROMOPROD_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES dbo.FIDE_PRODUCTOS_TB(ID_PRODUCTO),
    CONSTRAINT FK_PROMOPROD_PROMOCION FOREIGN KEY (ID_PROMOCION) REFERENCES dbo.FIDE_PROMOCIONES_TB(ID_PROMOCION),
    CONSTRAINT FK_PROMOPROD_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.[FIDE_RESEÑAS_TB]', 'U') IS NULL
CREATE TABLE dbo.[FIDE_RESEÑAS_TB] (
    [ID_RESEÑA] INT IDENTITY(1,1) NOT NULL,
    CALIFICACION INT NOT NULL,
    COMENTARIO NVARCHAR(500) NULL,
    FECHA DATETIME NOT NULL DEFAULT (GETDATE()),
    ID_USUARIO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT [PK_FIDE_RESEÑAS_TB] PRIMARY KEY ([ID_RESEÑA]),
    CONSTRAINT FK_RESENAS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.tbUsuario(Consecutivo),
    CONSTRAINT FK_RESENAS_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES dbo.FIDE_PRODUCTOS_TB(ID_PRODUCTO),
    CONSTRAINT FK_RESENAS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO),
    CONSTRAINT CK_RESENAS_CALIFICACION CHECK (CALIFICACION BETWEEN 1 AND 5)
);
GO

IF OBJECT_ID('dbo.FIDE_CONTACTOS_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_CONTACTOS_TB (
    ID_CONTACTO INT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(150) NOT NULL,
    CORREO NVARCHAR(150) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT (GETDATE()),
    ASUNTO NVARCHAR(150) NULL,
    MENSAJE NVARCHAR(1000) NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_CONTACTOS_TB PRIMARY KEY (ID_CONTACTO),
    CONSTRAINT FK_CONTACTOS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF OBJECT_ID('dbo.FIDE_PERSONAL_SHOPPER_TB', 'U') IS NULL
CREATE TABLE dbo.FIDE_PERSONAL_SHOPPER_TB (
    ID_SOLICITUD INT IDENTITY(1,1) NOT NULL,
    ESTILO_BUSCADO NVARCHAR(150) NULL,
    TALLA NVARCHAR(20) NULL,
    PRESUPUESTO DECIMAL(18,2) NOT NULL,
    NECESIDADES NVARCHAR(500) NULL,
    FECHA DATETIME NOT NULL DEFAULT (GETDATE()),
    ID_USUARIO INT NOT NULL,
    ID_ESTADO INT NOT NULL,
    CONSTRAINT PK_FIDE_PERSONAL_SHOPPER_TB PRIMARY KEY (ID_SOLICITUD),
    CONSTRAINT FK_PSHOPPER_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.tbUsuario(Consecutivo),
    CONSTRAINT FK_PSHOPPER_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES dbo.FIDE_ESTADOS_TB(ID_ESTADO)
);
GO

IF NOT EXISTS (SELECT 1 FROM dbo.FIDE_ESTADOS_TB WHERE NOMBRE_ESTADO = N'Activo')
    INSERT INTO dbo.FIDE_ESTADOS_TB (NOMBRE_ESTADO) VALUES (N'Activo');

IF NOT EXISTS (SELECT 1 FROM dbo.FIDE_ESTADOS_TB WHERE NOMBRE_ESTADO = N'Inactivo')
    INSERT INTO dbo.FIDE_ESTADOS_TB (NOMBRE_ESTADO) VALUES (N'Inactivo');
GO