//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Grupo02.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbError
    {
        public int Consecutivo { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Lugar { get; set; }
        public int ConsecutivoUsuario { get; set; }
    }
}
