//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Grupo02.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public int Consecutivo { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string Contrasenna { get; set; }
        public bool Estado { get; set; }
        public bool TieneContrasennaTemp { get; set; }
        public Nullable<System.DateTime> VigenciaContrasennaTemp { get; set; }
        public int ConsecutivoRol { get; set; }
    
        public virtual tbRol tbRol { get; set; }
    }
}
